# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-23 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='demographics',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
